name: CI and CD

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version-file: ".node-version"
            - uses: pnpm/action-setup@v2
              with:
                  run_install: |
                      - args: [--frozen-lockfile, --strict-peer-dependencies]

            - run: pnpm exec dprint check
            - run: pnpm run build

            - run: npm publish
              if: startsWith(github.ref, 'refs/tags/v')
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
